In [1]:
import tensorflow as tf
a=tf.constant(2,name="a")
b=tf.constant(3,name="b")
x=tf.add(a,b,name='add')
writer=tf.summary.FileWriter('./graphs',sess.graph)
with tf.Session() as sess:
    print(sess.run(x))

/usr/local/miniconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/local/miniconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


5


In [2]:
!tensorboard --logdir="./graphs/"

/usr/local/miniconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/local/miniconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
TensorBoard 1.9.0 at http://userdeMBP.lan:6006 (Press CTRL+C to quit)
^C


In [4]:
#tf.constant(value, dtype=None, shape=None, name='Const', verify_shape=False)
try:
    a=tf.constant(2,shape=[2,2],verify_shape=True)
except TypeError as e:
    print(e)
a=tf.constant(2,shape=[2,2],verify_shape=False)
tf.InteractiveSession()
a.eval()

Expected Tensor's shape: (2, 2), got ().


array([[2, 2],
       [2, 2]], dtype=int32)

In [5]:
a=tf.truncated_normal([2,3])
a.eval()

array([[-0.56975085,  0.56736004,  0.48184615],
       [-0.9145103 , -0.11045908, -0.15712465]], dtype=float32)

In [6]:
tf.random_shuffle(a)
a.eval()

array([[-0.17456752, -1.1397517 , -0.56743026],
       [ 0.8461719 , -0.30486545,  0.74147063]], dtype=float32)

In [ ]:
# huber loss
'''
for |y-y_pred|<delta   1/2*(y-y_pred)^2
otherwise              delta*|y-y_pred|-1/2*delta^2
'''

def huber_loss(label,pred,delta=1.0):
    residual=tf.abs(label-pred)
    condition=tf.less_equal(residual,delta)
    small_loss=0.5*tf.square(residual)
    large_loss=delta*residual-0.5*tf.square(delta)
    return tf.where(condition,small_loss,large_loss)